# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite_identifier', models.CharField(max_length=255)),
                ('remaining_items', models.IntegerField()),
                ('product_description', models.CharField(max_length=255)),
                ('product_attribute_list', models.TextField()),
            ],
        ),
    ]
