# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_attribute_list',
            new_name='attribute_list',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
