# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_order_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute_list',
            new_name='attribute_dict',
        ),
    ]
