# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_auto_20170428_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_identifier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='payment_app.Order'),
        ),
    ]
