# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_auto_20170501_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sprite_identifier',
            new_name='stripe_identifier',
        ),
    ]
