# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0009_auto_20170501_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
